# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numFactura', models.CharField(max_length=16)),
                ('empresa', models.CharField(max_length=30)),
                ('fechaMax', models.DateField()),
                ('cantidad', models.FloatField()),
                ('estado', models.CharField(max_length=10)),
            ],
        ),
    ]
