# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numRecibo', models.CharField(max_length=16)),
                ('fechaPago', models.DateField()),
                ('cantidad', models.FloatField()),
                ('cliente', models.CharField(max_length=50)),
                ('concepto', models.CharField(max_length=200)),
            ],
        ),
    ]
